name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install


  sast:
    name: SAST - SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=anushh13_secure-pipeline-demo
            -Dsonar.organization=anushh13
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  dast:
    name: DAST - OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://example.com"
